version: "3.7"

services:
  mysql:
    image: percona
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=zeta
      - MYSQL_PASSWORD=zeta
      - MYSQL_DATABASE=absenceManager
      - MYSQL_ROOT_PASSWORD=zeta