spring:
  datasource:
    url: jdbc:mysql://localhost:3306/absenceManager
    username: root
    password: linuxconfig.org
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      use-new-id-generator-mappings: false
      ddl-auto: create
